afriqapp/urls.py
from django.urls import  path
from . import views

app_name = 'afriqapp'

urlpatterns = [
    path('',views.MemberListview.as_view(), name='index'),
    path('add-member', views.MembersCreateView.as_view(), name='add-member'),
    path('<int:pk>/update', views.MembersUpdateView.as_view(), name='update-member'),
    path('<int:pk>/delete', views.MembersDeleteView.as_view(), name='delete-member'),

]

raph/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('afriqapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

afriqapp/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
class Members(models.Model):
    name = models.CharField(max_length=40)
    occupation = models.CharField(max_length=40)
    slogan = models.CharField(max_length=40)
    residence = models.CharField(max_length=40)
    photo = models.ImageField()
    course = models.CharField(max_length=40)
    hobby = models.CharField(max_length=40)
    is_male = models.BooleanField(default=True)
    age = models.IntegerField()
    nationality = models.CharField(max_length=40)
    primary = models.CharField(max_length=40)
    secondary = models.CharField(max_length=40)
    email = models.EmailField(max_length=40)


    def _str_(self):
        return self.name
    def get_absolute_url(self):
        return reverse('afriqapp:index')

afriqapp/views.py
from django.shortcuts import render
from .models import Members
from django . views . generic import ListView, CreateView, UpdateView, DeleteView

# Create your views here.
#def index(request):
    #profiles = Members.objects.all()
    #return render(request, 'afriqapp/index.html', {'profiles':profiles})
class MemberListview(ListView):
    model = Members
    template_name = 'afriqapp/index.html'
    context_object_name = 'profiles'
    odering = ['name']
    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Members.objects.filter(name__icontains=query)
        else:
            return Members.objects.all()

class MembersCreateView(CreateView):
        model = Members
        fields = '__all__'
class MembersUpdateView(UpdateView):
    model = Members
    fields = '__all__'
class MembersDeleteView(DeleteView):
    model = Members
    success_url = '/'

afriqapp/templates/afriqapp/base.html
<html lang="en">

<head>

<title>{% block title %}{% endblock %}</title>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

<link href='https://fonts.googleapis.com/css?family=Cabin Sketch' rel='stylesheet'>

<link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet'>

<link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>

<link href='https://fonts.googleapis.com/css?family=Bree Serif' rel='stylesheet'>

<link href='https://fonts.googleapis.com/css?family=ZCOOL KuaiLe' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Indie Flower' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Shadows Into Light' rel='stylesheet'>

{% load static %}
 <link rel="stylesheet" href="{% static 'afriqapp/css/style.css' %}"type="text/css">


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>



<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>



<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">

    <span class="navbar-toggler-icon"></span>

  </button>

  <a class="navbar-brand" href="{% url 'afriqapp:add-member' %}" style="font-family: 'Acme', cursive;">PYTHON MEMBERS</a>



  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">

    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

    <li class="nav-item">

    <form class="form-inline my-2 my-lg-0">

      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.GET.q }}">

      <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>

    </form>

        </li>

    </ul>

    <ul class="navbar-nav">

        <li class="nav-item active">

      <a class="nav-link" href="" style="font-family: 'Orbirton', cursive;"><i class="fas fa-user-plus" style="color: steelblue;"></i> Add Member<span class="sr-only">(current)</span></a>

      </li>

      <li class="nav-item active">

      <a class="nav-link" href="url 'afriqapp:index'" style="font-family: 'Orbirton', cursive;"><i class="fas fa-sign-out-alt" style="color: red;"></i> Logout<span class="sr-only">(current)</span></a>

      </li>



    </ul>

  </div>

</nav>

<div class="container">



    {% block content %}



    {% endblock %}





</div>







</body>

afriqapp/templates/afriqapp/index.html
{% extends 'afriqapp/base.html' %}
{% block title %}python members{% endblock %}

{% block content %}
<div class="row" xmlns="http://www.w3.org/1999/html">
        {% if profiles%}
            {% for prof in profiles %}
                <div class="col-sm-3">
                    <div class="card card-body my-3"style="background-colour: {% if prof.is_male %}blue; {%  else %}purple;{% endif %}">
                        <h4 class="text-center"style="white-space: nowrap; overflow: hidden; border-bottom:1px; max-width:90; font-family:ZCOOL KuaiLe">{{ prof.name }}</h4 >


                        <hr>
                        <img src="{{prof.photo.url}}" class="rounded-circle mx-auto img-fluid" alt="" style="height:130px; width:130px;">
                        <div class="caption">
                            <h5 class="text-center">{{prof.occupation}}</h5>
                             <h6 class="text-center" style="white-space: nowrap; overflow: hidden; border-bottom:1px; max-width:90; font-family:Indie Flower">{{prof.slogan}}</h6>
                            <a href="" class="btn btn-info btn-sm" data-toggle="modal"data-target="#modal">
                                <i class="fas fa-info"></i>
                            </a>
                            <a href="{% url 'afriqapp:delete-member' prof.id%}" class="btn btn-danger btn-sm" style="float: right;">
                                <i class="fas fa-trash"></i>
                            </a>

                        </div>

                    </div>

                    <!--Modal -->
                    <div class="modal fade" id="modal" role="dialog">
                        <div class="modal-dialog">
                        <div class="modal-content">
                             <div class="modal-header">
                            <h4 class="modal-title">{{prof.name}}</h4>
                                <button type="button" class="close" data-dismiss="modal">&times;</button></h4>
                        </div>
                            <div class="modal-body">
                            <p class="text-center"style="font-family:Indie Flower">{{prof.name}} is age  {{prof.age}}.He is a {{prof.nationality}} citizen.He went to {{prof.primary}} then later joined {{prof.secondary}}.{{prof.name}} is a {{prof.occupation}} by proffesion.He lives in {{prof.residence}}. You can contact him at <a href="mailto: {{prof.email}}">{{prof.email}}</a>. His slogan is {{prof.slogan}}.</p>

                    </div>
                        <div class="modal-footer">
                         <a href="{% url 'afriqapp:update-member' prof.id %}" class="btn btn-outline primary btn-sm">
                             <i class="fas fa-edit"></i>
                            </a>
                        </div>
                        </div>

                    </div>
                    </div>

                 </div>

            {%endfor %}
        {%endif %}
    </div>
{% endblock %}

afriqapp/templates/afriqapp/members_confirm_delete.html
{% extends 'afriqapp/base.html' %}

{% block title %}Delete{{object.name}}{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-3"></div>
            <div class="col-sm-6">
                <div class="card card-body my-1">
                    <h3>Delete <b>{{ object.name }}</b>?</h3>
                    <hr>
                    <form method="post" class="form-horizontal">
                        {% csrf_token %}
                        <div class="form-group">
                            <button type="submit" class="btn btn-danger">Delete</button>
                            <a href="{% url 'afriqapp:index' %}" class="btn btn-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

afriqapp/templates/afriqapp/members_form.html
{% extends 'afriqapp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}{% if object %}Update {{object.name}}{% else %} Add member {% endif %}{% endblock %}
{% block content %}

    <div class="row">
        <div class="col-sm-3"></div>
            <div clas="col-sm-6">
                <div class="card card-body">
                    <h3 class="text-capitalize">{% if object %}Update {{object.name}}{% else %} Add member {% endif %}</h3>
                    <hr>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form|crispy}}

                        <div class="form-group">
                            <button type="submit" class="btn btn-info">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}